import Foundation

struct StructuredReport: Codable, Identifiable, Hashable {
    /// Sentinel string used in `patientSummary` to flag reports that
    /// were short-circuited because the scanned content didn't look
    /// like a lab report at all. Surfaced to the UI via
    /// `wasRejectedAsNonHealth` so ScanView can show an alert popup
    /// instead of pushing into the (empty) DashboardView.
    static let nonHealthRejectionMarker = "__LOCALABS_NON_HEALTH_REJECTED__"

    var id: UUID
    var timestamp: Date
    /// Short title generated by the model and shown in the History
    /// row + report header. Default empty for older reports that
    /// pre-date the feature; `displayTitle` falls back to a date-
    /// based label in that case so the UI stays consistent.
    /// Editable via the History row's Rename action.
    var title: String
    var patientSummary: String
    var doctorQuestions: String
    var dietaryAdvice: String
    var medicalGlossary: String
    var medicationNotes: String
    var rawText: String
    var imagePath: String?
    /// Additional page filenames for multi-page scans (PDFs or multiple
    /// photos). The first page's path stays in `imagePath` so existing
    /// saved reports decode unchanged.
    var additionalPagePaths: [String]?

    /// Structured lab measurements extracted from this report (#28).
    /// Optional so reports saved before extraction existed still decode
    /// — Swift's synthesized decoder treats a missing optional key as
    /// nil rather than failing. nil = never extracted; [] = extracted,
    /// found nothing trackable.
    var labValues: [LabValue]?

    /// The date printed ON the report (collection / draw date), parsed
    /// from the OCR text at scan time. This — not the scan time — is
    /// the clinically correct ordering for trends: scanning an old
    /// report after a newer one should still place it earlier in the
    /// progression. nil when no date could be parsed; `effectiveDate`
    /// falls back to `timestamp` in that case.
    var reportDate: Date?

    /// True when the analysis pipeline refused this scan because it
    /// didn't contain any lab values, units, or medical vocabulary.
    /// Drives the "No health content detected" popup in ScanView.
    /// Checked via a marker in `patientSummary` so we don't have to
    /// change the Codable surface (older saved reports stay decodable).
    var wasRejectedAsNonHealth: Bool {
        patientSummary.contains(Self.nonHealthRejectionMarker)
    }

    init(
        id: UUID = UUID(),
        timestamp: Date = Date(),
        title: String = "",
        patientSummary: String = "",
        doctorQuestions: String = "",
        dietaryAdvice: String = "",
        medicalGlossary: String = "",
        medicationNotes: String = "",
        rawText: String = "",
        imagePath: String? = nil,
        additionalPagePaths: [String]? = nil,
        labValues: [LabValue]? = nil,
        reportDate: Date? = nil,
        belongsToOther: Bool? = nil,
        reportPatientAge: Int? = nil,
        reportPatientSex: String? = nil,
        detectedMedications: [DetectedMedication]? = nil
    ) {
        self.id = id
        self.timestamp = timestamp
        self.title = title
        self.patientSummary = patientSummary
        self.doctorQuestions = doctorQuestions
        self.dietaryAdvice = dietaryAdvice
        self.medicalGlossary = medicalGlossary
        self.medicationNotes = medicationNotes
        self.rawText = rawText
        self.imagePath = imagePath
        self.additionalPagePaths = additionalPagePaths
        self.labValues = labValues
        self.reportDate = reportDate
        self.belongsToOther = belongsToOther
        self.reportPatientAge = reportPatientAge
        self.reportPatientSex = reportPatientSex
        self.detectedMedications = detectedMedications
    }

    /// The date to use for trend ordering: the date printed on the
    /// report when we could parse it, otherwise the scan time.
    var effectiveDate: Date { reportDate ?? timestamp }

    /// True when this report belongs to someone OTHER than the app
    /// user (e.g. they scanned a parent's labs). Such reports are
    /// excluded from the user's cross-report trends and from the chat
    /// context, and tagged in History. nil/false = the user's own.
    /// Set manually by the user, optionally prompted by an age mismatch.
    var belongsToOther: Bool?

    /// The patient age printed on the report, if found at scan time.
    /// Used only to *suggest* (not decide) that a report might be
    /// someone else's when it clearly can't match the user's age.
    var reportPatientAge: Int?

    /// The patient sex printed on the report ("Male"/"Female"), if
    /// found at scan time. Like `reportPatientAge`, used only to
    /// suggest the report might be someone else's when it conflicts
    /// with the user's biological sex.
    var reportPatientSex: String?

    /// Medications EXPLICITLY named in this document (a prescription,
    /// after-visit summary, or current-meds list), extracted copy-only
    /// at scan time. Surfaced on the dashboard as one-tap "Add to Meds"
    /// suggestions — Localabs never invents a medication, so this only
    /// holds names that literally appear in the scanned text. nil =
    /// never extracted (older reports); [] = extracted, none found.
    var detectedMedications: [DetectedMedication]?

    /// Convenience: whether this report counts toward the user's own
    /// trends / chat context.
    var isOwnReport: Bool { belongsToOther != true }

    /// Title shown in History rows + the Dashboard header. Three tiers:
    ///   1. User-set `title` from the History row's Rename action
    ///   2. Lab-panel / clinical-note keyword detected in the raw OCR
    ///      text — deterministic regex match against common panel +
    ///      diagnosis names. This is the default for any new scan
    ///      since the LLM no longer generates a title (that feature
    ///      was unreliable on a 4B model — it tended to latch onto
    ///      whichever noun appeared most often, not the document's
    ///      actual subject).
    ///   3. Date-based label (last resort, for scans whose OCR
    ///      doesn't match any known keyword)
    var displayTitle: String {
        let trimmed = title.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty { return trimmed }
        if let derived = Self.titleFromOCRKeywords(rawText), !derived.isEmpty {
            return derived
        }
        let formatter = DateFormatter()
        formatter.dateFormat = "MMMM d 'Report'"
        return formatter.string(from: timestamp)
    }

    /// Scans the entire OCR text for common lab-panel keywords and
    /// returns a clean human-readable title when one matches. Patterns
    /// are ordered most-specific-first so "Comprehensive Metabolic
    /// Panel" wins over a bare "Metabolic Panel" hit.
    ///
    /// This is the default title path for every new scan now that
    /// the LLM-side `[TITLE: …]` feature was removed for reliability
    /// reasons. The History row reflects what the report actually
    /// IS by pattern-matching the OCR against a curated list of
    /// panel + diagnosis names.
    private static func titleFromOCRKeywords(_ ocrText: String) -> String? {
        guard !ocrText.isEmpty else { return nil }
        let lower = ocrText.lowercased()
        let patterns: [(needles: [String], title: String)] = [
            // Lab-report patterns (specific panels first)
            (["comprehensive metabolic panel", "cmp panel"], "Comprehensive Metabolic Panel"),
            (["basic metabolic panel", "bmp panel"], "Basic Metabolic Panel"),
            (["complete blood count", "cbc panel", "cbc with diff", "cbc w/ diff"], "Complete Blood Count"),
            (["lipid panel", "lipid profile"], "Lipid Panel Results"),
            (["hemoglobin a1c", "hba1c", " a1c"], "Hemoglobin A1C Test"),
            (["thyroid panel", "thyroid function", "tsh,"], "Thyroid Panel"),
            (["vitamin d, 25", "25-hydroxyvitamin d", "vitamin d test"], "Vitamin D Test"),
            (["vitamin b12"], "Vitamin B12 Test"),
            (["liver function", "hepatic panel", "liver panel"], "Liver Function Panel"),
            (["kidney function", "renal panel", "renal function"], "Renal Function Panel"),
            (["iron panel", "iron studies", "ferritin"], "Iron Panel"),
            (["urinalysis"], "Urinalysis"),
            (["psa, total", "prostate specific antigen"], "PSA Test"),
            (["estradiol"], "Estradiol Test"),
            (["testosterone"], "Testosterone Test"),
            (["cortisol"], "Cortisol Test"),
            (["c-reactive protein", "crp,"], "C-Reactive Protein"),

            // Clinical-note patterns — diagnosis keywords from
            // common encounter notes. Used the same way as the lab-
            // panel patterns above: the History row labels itself
            // from whichever clinical term matches the OCR text.
            (["vitiligo", "icd-10: l80", "icd 10 l80"], "Vitiligo Evaluation"),
            (["psoriasis", "icd-10: l40"], "Psoriasis Evaluation"),
            (["eczema", "atopic dermatitis"], "Eczema Evaluation"),
            (["hashimoto"], "Hashimoto's Thyroiditis Visit"),
            (["graves' disease", "graves disease"], "Graves' Disease Visit"),
            (["diabetes mellitus", "type 2 diabetes", "type 1 diabetes"], "Diabetes Visit"),
            (["hypertension", "essential htn", "icd-10: i10"], "Hypertension Visit"),
            (["hyperlipidemia", "dyslipidemia"], "Hyperlipidemia Visit"),
            (["asthma"], "Asthma Visit"),
            (["copd", "chronic obstructive"], "COPD Visit"),
            (["rheumatoid arthritis"], "Rheumatoid Arthritis Visit"),
            (["osteoarthritis"], "Osteoarthritis Visit"),
            (["migraine"], "Migraine Visit"),
            (["depression", "major depressive"], "Depression Visit"),
            (["anxiety disorder"], "Anxiety Visit"),
            (["annual physical", "annual wellness"], "Annual Physical"),
            (["new patient evaluation"], "New Patient Visit"),
            (["follow-up visit", "follow up visit"], "Follow-Up Visit"),
        ]
        for (needles, title) in patterns {
            if needles.contains(where: { lower.contains($0) }) {
                return title
            }
        }
        return nil
    }

    /// True when the report's AI generation didn't produce a normal
    /// 5-section output. Detected by checking whether the patient summary
    /// matches our specific failure / cancellation messages OR every
    /// section is empty despite OCR text being present. Used by the
    /// dashboard to surface a "Resume Analysis" call-to-action.
    var isIncomplete: Bool {
        let hasOCR = !rawText.isEmpty
        // The Localabs prompt instructs the model to always produce
        // all five sections in order. Any missing section overwhelmingly
        // means generation was interrupted mid-stream — pause, app
        // backgrounded, or n_ctx overflow. A legit report on any
        // scanned lab panel produces at least placeholder text for
        // every section (the AI will say "Not applicable" rather than
        // emit nothing). So "any section empty" is the most reliable
        // truncation signal we have without adding an explicit flag.
        let anySectionEmpty = patientSummary.isEmpty
            || doctorQuestions.isEmpty
            || dietaryAdvice.isEmpty
            || medicalGlossary.isEmpty
            || medicationNotes.isEmpty
        let hasFailureMarker = patientSummary.contains("interrupted")
            || patientSummary.contains("didn't complete")
            || patientSummary.contains("Analysis was")
            || patientSummary.contains("Paused before")
            || patientSummary.contains("Failed to extract")
        return hasOCR && (anySectionEmpty || hasFailureMarker)
    }

    /// All page image URLs in document order. Empty if the report has no
    /// saved scans (e.g., weekly Apple Health review). Multi-page reports
    /// have one URL per page in chronological scan order.
    var allImageURLs: [URL] {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        let scansDir = docs.appendingPathComponent("scans")
        var urls: [URL] = []
        if let imagePath {
            urls.append(scansDir.appendingPathComponent(imagePath))
        }
        if let extras = additionalPagePaths {
            urls.append(contentsOf: extras.map { scansDir.appendingPathComponent($0) })
        }
        return urls
    }

    static func parse(from rawText: String) -> StructuredReport {
        // Title is no longer extracted from model output — the
        // [TITLE: …] feature was removed because small models
        // routinely produced unhelpful titles (single OCR keywords,
        // generic words). `displayTitle` now falls back to a
        // deterministic keyword-based detector over the raw OCR,
        // then a date-based label. The `title` field on
        // StructuredReport stays as the destination for the
        // History row's Rename action.
        let workingText = rawText

        let headers: [(key: String, patterns: [String])] = [
            ("patientSummary",   ["PATIENT SUMMARY"]),
            ("doctorQuestions",  ["QUESTIONS FOR YOUR DOCTOR", "QUESTIONS FOR THE DOCTOR"]),
            ("dietaryAdvice",    ["TARGETED DIETARY ADVICE", "DIETARY ADVICE"]),
            ("medicalGlossary",  ["MEDICAL GLOSSARY", "GLOSSARY"]),
            ("medicationNotes",  ["MEDICATION NOTES", "MEDICATIONS"]),
        ]

        var sections: [String: String] = [:]
        let lines = workingText.components(separatedBy: .newlines)
        var currentKey: String?
        var buffer: [String] = []

        func flush() {
            if let key = currentKey {
                let value = buffer.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
                if !value.isEmpty {
                    // Append on repeat instead of overwriting. The model
                    // occasionally restarts a section on multi-page
                    // scans — emits PATIENT SUMMARY for page 1, then
                    // emits PATIENT SUMMARY again when it hits the
                    // [Page 2] marker. The prompt now forbids this, but
                    // if it leaks through, merging preserves both
                    // chunks instead of clobbering page 1's content
                    // with page 2's.
                    if let existing = sections[key], !existing.isEmpty {
                        sections[key] = "\(existing)\n\n\(value)"
                    } else {
                        sections[key] = value
                    }
                }
            }
            buffer.removeAll(keepingCapacity: true)
        }

        for line in lines {
            let stripped = line.trimmingCharacters(in: .whitespaces)
                .replacingOccurrences(of: "*", with: "")
                .replacingOccurrences(of: "#", with: "")
                .trimmingCharacters(in: .whitespaces)
            let upper = stripped.uppercased()

            var matchedKey: String?
            // Strip BOTH the numbering prefix ("5.", "5)") AND any
            // leading non-letter glyphs (stray emoji like "💊", bullet
            // chars, dashes) before pattern-matching the header. The
            // model's prompt allows section-internal emoji and it
            // occasionally leaks a 💊 onto the "MEDICATION NOTES"
            // header line — previously that stranded the section as
            // empty because the prefix check failed, which then
            // tripped isIncomplete and blocked navigation to
            // Dashboard.
            let withoutNumbering = upper
                .replacingOccurrences(
                    of: #"^[^A-Z]+"#,
                    with: "",
                    options: .regularExpression
                )
            for header in headers {
                for pattern in header.patterns {
                    if withoutNumbering.hasPrefix(pattern) {
                        matchedKey = header.key
                        break
                    }
                }
                if matchedKey != nil { break }
            }

            if let key = matchedKey {
                flush()
                currentKey = key
            } else {
                buffer.append(line)
            }
        }
        flush()

        // title defaults to "" — displayTitle handles the keyword-
        // detector + date fallback so the History row always reads
        // something meaningful even without a manually-set title.
        return StructuredReport(
            patientSummary: sections["patientSummary"] ?? workingText.trimmingCharacters(in: .whitespacesAndNewlines),
            doctorQuestions: sections["doctorQuestions"] ?? "",
            dietaryAdvice: sections["dietaryAdvice"] ?? "",
            medicalGlossary: sections["medicalGlossary"] ?? "",
            medicationNotes: sections["medicationNotes"] ?? "",
            rawText: rawText
        )
    }
}

/// A medication Localabs found explicitly written in a scanned
/// document — a name, plus the dose and frequency when the document
/// states them. Surfaced on the dashboard as a one-tap "Add to Meds"
/// suggestion that pre-fills the medication editor. Copy-only: every
/// field comes verbatim from the document, never inferred.
struct DetectedMedication: Codable, Equatable, Hashable, Identifiable {
    var name: String
    var dose: String
    var frequency: String

    /// Stable identity from the content (no stored UUID, so it stays
    /// clean through Codable round-trips and dedupes naturally).
    var id: String { "\(name)|\(dose)|\(frequency)".lowercased() }
}
