import Foundation

struct StructuredReport: Codable, Identifiable, Hashable {
    /// Sentinel string used in `patientSummary` to flag reports that
    /// were short-circuited because the scanned content didn't look
    /// like a lab report at all. Surfaced to the UI via
    /// `wasRejectedAsNonHealth` so ScanView can show an alert popup
    /// instead of pushing into the (empty) DashboardView.
    static let nonHealthRejectionMarker = "__LOCALABS_NON_HEALTH_REJECTED__"

    var id: UUID
    var timestamp: Date
    /// Short title generated by the model and shown in the History
    /// row + report header. Default empty for older reports that
    /// pre-date the feature; `displayTitle` falls back to a date-
    /// based label in that case so the UI stays consistent.
    /// Editable via the History row's Rename action.
    var title: String
    var patientSummary: String
    var doctorQuestions: String
    var dietaryAdvice: String
    var medicalGlossary: String
    var medicationNotes: String
    var rawText: String
    var imagePath: String?
    /// Additional page filenames for multi-page scans (PDFs or multiple
    /// photos). The first page's path stays in `imagePath` so existing
    /// saved reports decode unchanged.
    var additionalPagePaths: [String]?

    /// True when the analysis pipeline refused this scan because it
    /// didn't contain any lab values, units, or medical vocabulary.
    /// Drives the "No health content detected" popup in ScanView.
    /// Checked via a marker in `patientSummary` so we don't have to
    /// change the Codable surface (older saved reports stay decodable).
    var wasRejectedAsNonHealth: Bool {
        patientSummary.contains(Self.nonHealthRejectionMarker)
    }

    init(
        id: UUID = UUID(),
        timestamp: Date = Date(),
        title: String = "",
        patientSummary: String = "",
        doctorQuestions: String = "",
        dietaryAdvice: String = "",
        medicalGlossary: String = "",
        medicationNotes: String = "",
        rawText: String = "",
        imagePath: String? = nil,
        additionalPagePaths: [String]? = nil
    ) {
        self.id = id
        self.timestamp = timestamp
        self.title = title
        self.patientSummary = patientSummary
        self.doctorQuestions = doctorQuestions
        self.dietaryAdvice = dietaryAdvice
        self.medicalGlossary = medicalGlossary
        self.medicationNotes = medicationNotes
        self.rawText = rawText
        self.imagePath = imagePath
        self.additionalPagePaths = additionalPagePaths
    }

    /// Title shown in History rows + the Dashboard header. Three tiers:
    ///   1. LLM-generated `title` (best — descriptive, panel-specific)
    ///   2. First bullet/sentence of patientSummary, truncated (good — at
    ///      least tells the user what the report *says* even when the
    ///      model skipped the [TITLE: …] line)
    ///   3. Date-based label (last resort)
    /// The middle tier replaces what used to be the only fallback. The
    /// user found pure date titles uninformative when the model
    /// occasionally omitted the structured title marker.
    var displayTitle: String {
        let trimmed = title.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty { return trimmed }
        if let derived = Self.deriveFallbackTitle(from: patientSummary), !derived.isEmpty {
            return derived
        }
        let formatter = DateFormatter()
        formatter.dateFormat = "MMMM d 'Lab Report'"
        return formatter.string(from: timestamp)
    }

    /// Pulls a short, single-line title out of the first meaningful bullet
    /// of a streamed patient summary. Strips bullet glyphs and markdown
    /// emphasis, caps the length so it fits on a History row, and returns
    /// nil if there's nothing usable to derive from.
    private static func deriveFallbackTitle(from patientSummary: String) -> String? {
        let firstLine = patientSummary
            .components(separatedBy: .newlines)
            .lazy
            .map { line -> String in
                var s = line.trimmingCharacters(in: .whitespacesAndNewlines)
                let bulletPrefixes = ["- ", "* ", "• ", "– ", "— "]
                for prefix in bulletPrefixes where s.hasPrefix(prefix) {
                    s = String(s.dropFirst(prefix.count))
                    break
                }
                return s
                    .replacingOccurrences(of: "**", with: "")
                    .replacingOccurrences(of: "*", with: "")
                    .replacingOccurrences(of: "`", with: "")
                    .trimmingCharacters(in: .whitespacesAndNewlines)
            }
            .first { !$0.isEmpty }
        guard let line = firstLine else { return nil }
        if line.count <= 48 { return line }
        return String(line.prefix(46)) + "…"
    }

    var imageURL: URL? {
        guard let imagePath else { return nil }
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        return docs.appendingPathComponent("scans").appendingPathComponent(imagePath)
    }

    /// True when the report's AI generation didn't produce a normal
    /// 5-section output. Detected by checking whether the patient summary
    /// matches our specific failure / cancellation messages OR every
    /// section is empty despite OCR text being present. Used by the
    /// dashboard to surface a "Resume Analysis" call-to-action.
    var isIncomplete: Bool {
        let hasOCR = !rawText.isEmpty
        // The Localabs prompt instructs the model to always produce
        // all five sections in order. Any missing section overwhelmingly
        // means generation was interrupted mid-stream — pause, app
        // backgrounded, or n_ctx overflow. A legit report on any
        // scanned lab panel produces at least placeholder text for
        // every section (the AI will say "Not applicable" rather than
        // emit nothing). So "any section empty" is the most reliable
        // truncation signal we have without adding an explicit flag.
        let anySectionEmpty = patientSummary.isEmpty
            || doctorQuestions.isEmpty
            || dietaryAdvice.isEmpty
            || medicalGlossary.isEmpty
            || medicationNotes.isEmpty
        let hasFailureMarker = patientSummary.contains("interrupted")
            || patientSummary.contains("didn't complete")
            || patientSummary.contains("Analysis was")
            || patientSummary.contains("Paused before")
            || patientSummary.contains("Failed to extract")
        return hasOCR && (anySectionEmpty || hasFailureMarker)
    }

    /// All page image URLs in document order. Empty if the report has no
    /// saved scans (e.g., weekly Apple Health review). Multi-page reports
    /// have one URL per page in chronological scan order.
    var allImageURLs: [URL] {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        let scansDir = docs.appendingPathComponent("scans")
        var urls: [URL] = []
        if let imagePath {
            urls.append(scansDir.appendingPathComponent(imagePath))
        }
        if let extras = additionalPagePaths {
            urls.append(contentsOf: extras.map { scansDir.appendingPathComponent($0) })
        }
        return urls
    }

    static func parse(from rawText: String) -> StructuredReport {
        // Pull the model-generated title (if any) out of the leading
        // `[TITLE: "..."]` marker. We try multiple patterns so small-
        // model drift (missing quotes, missing brackets, markdown
        // wrapping) doesn't strand the report with the date-based
        // fallback.
        //
        // Patterns tried in order:
        //   1. [TITLE: "..."] or [TITLE: ...]   (canonical + bracketless-quote)
        //   2. TITLE: "..." or TITLE: ...        (bracket-less, line-anchored)
        // First match wins. Both strip the matched text from the
        // section-parsing input so the title doesn't get folded into
        // PATIENT SUMMARY.
        var extractedTitle: String = ""
        var workingText = rawText
        let titlePatterns = [
            #"\[\s*TITLE\s*:\s*["']?([^"'\]\n]+?)["']?\s*\]"#,
            #"(?m)^\s*\**\s*TITLE\s*:\s*["']?([^"'\n]+?)["']?\s*\**\s*$"#,
        ]
        for pattern in titlePatterns {
            guard let regex = try? NSRegularExpression(pattern: pattern, options: []) else { continue }
            let nsRange = NSRange(workingText.startIndex..., in: workingText)
            if let match = regex.firstMatch(in: workingText, range: nsRange),
               match.numberOfRanges >= 2,
               let captureRange = Range(match.range(at: 1), in: workingText) {
                let raw = String(workingText[captureRange])
                extractedTitle = raw
                    .replacingOccurrences(of: "**", with: "")
                    .replacingOccurrences(of: "*", with: "")
                    .replacingOccurrences(of: "`", with: "")
                    .trimmingCharacters(in: .whitespacesAndNewlines)
                workingText = regex.stringByReplacingMatches(
                    in: workingText,
                    options: [],
                    range: nsRange,
                    withTemplate: ""
                ).trimmingCharacters(in: .whitespacesAndNewlines)
                if !extractedTitle.isEmpty { break }
            }
        }

        let headers: [(key: String, patterns: [String])] = [
            ("patientSummary",   ["PATIENT SUMMARY"]),
            ("doctorQuestions",  ["QUESTIONS FOR YOUR DOCTOR", "QUESTIONS FOR THE DOCTOR"]),
            ("dietaryAdvice",    ["TARGETED DIETARY ADVICE", "DIETARY ADVICE"]),
            ("medicalGlossary",  ["MEDICAL GLOSSARY", "GLOSSARY"]),
            ("medicationNotes",  ["MEDICATION NOTES", "MEDICATIONS"]),
        ]

        var sections: [String: String] = [:]
        let lines = workingText.components(separatedBy: .newlines)
        var currentKey: String?
        var buffer: [String] = []

        func flush() {
            if let key = currentKey {
                let value = buffer.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
                sections[key] = value
            }
            buffer.removeAll(keepingCapacity: true)
        }

        for line in lines {
            let stripped = line.trimmingCharacters(in: .whitespaces)
                .replacingOccurrences(of: "*", with: "")
                .replacingOccurrences(of: "#", with: "")
                .trimmingCharacters(in: .whitespaces)
            let upper = stripped.uppercased()

            var matchedKey: String?
            // Strip BOTH the numbering prefix ("5.", "5)") AND any
            // leading non-letter glyphs (stray emoji like "💊", bullet
            // chars, dashes) before pattern-matching the header. The
            // model's prompt allows section-internal emoji and it
            // occasionally leaks a 💊 onto the "MEDICATION NOTES"
            // header line — previously that stranded the section as
            // empty because the prefix check failed, which then
            // tripped isIncomplete and blocked navigation to
            // Dashboard.
            let withoutNumbering = upper
                .replacingOccurrences(
                    of: #"^[^A-Z]+"#,
                    with: "",
                    options: .regularExpression
                )
            for header in headers {
                for pattern in header.patterns {
                    if withoutNumbering.hasPrefix(pattern) {
                        matchedKey = header.key
                        break
                    }
                }
                if matchedKey != nil { break }
            }

            if let key = matchedKey {
                flush()
                currentKey = key
            } else {
                buffer.append(line)
            }
        }
        flush()

        return StructuredReport(
            title: extractedTitle,
            patientSummary: sections["patientSummary"] ?? workingText.trimmingCharacters(in: .whitespacesAndNewlines),
            doctorQuestions: sections["doctorQuestions"] ?? "",
            dietaryAdvice: sections["dietaryAdvice"] ?? "",
            medicalGlossary: sections["medicalGlossary"] ?? "",
            medicationNotes: sections["medicationNotes"] ?? "",
            rawText: rawText
        )
    }
}
